### PR TITLE
Added ML.NET + Chat Bot slides

### PR DESCRIPTION
**Pull request by Veroni4ka**
Added slides from the "How To Integrate ML.NET with a Chat Bot" session

### CODE REVIEW

**Comment by cheahengsoon** [comment]
@Veroni4ka May share the code ? Thank you.

**Comment by cheahengsoon** [comment]
I had create my own source code.
https://github.com/cheahengsoon/IntegrateML.NetwithBotServices

**Comment by Veroni4ka** [comment]
@cheahengsoon Here's the code I used for my demo https://github.com/Veroni4ka/MLNetBot

**Comment by compuwizpiyu** [comment]
@Veroni4ka, thanks for sharing the code used for demo :)

**Pull request merged**
